version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 3333:3333
    environment:
      PORT: 3333
      DATABASE_URL: postgres://movy:movy@database/movy
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: movy
      POSTGRES_PASSWORD: movy
      POSTGRES_DB: movy
